apiVersion: v1
kind: Secret
metadata:
  name: kproxy-env
type: Opaque
immutable: true
### Unencoded
stringData:
  KENTIK_API_TOKEN: < API Token >
  KENTIK_API_EMAIL: < kproxy Email >
  KENTIK_REGION: < UIS or EU >
### OR base64 encoded secrets
#data:
#  KENTIK_API_TOKEN: < echo -n "<API TOKEN>" | base64 >
#  KENTIK_API_EMAIL: < echo -n "<API Email>" | base64 >
#  KENTIK_REGION: < echo -n "<REGION>" | base64 >

---
apiVersion: v1
kind: Pod
metadata:
  name: kentik-kproxy
  labels:
    app: kproxy
spec:
  hostname: k8s-proxy
  containers:
  - name: kentik-kproxy
    image: kentik/kproxy:latest
    envFrom:
      - secretRef:
          name: kproxy-env
    args:
    - "-api_email=$(KENTIK_API_EMAIL)"
    - "-host=0.0.0.0"
    - "-healthcheck=0.0.0.0"
    - "-region=$(KENTIK_REGION)"
    
---
apiVersion: v1
kind: Service
metadata:
  name: kentik-kproxy
  labels:
    app: kproxy
spec:
  selector:
    app: kproxy
  externalTrafficPolicy: Local
  ports:
  - name: kproxy-hc
    protocol: TCP
    targetPort: 9996
    port: 9996
    nodePort: 30996
  - name: kproxy
    protocol: UDP
    targetPort: 9995
    port: 9995
    nodePort: 30995
  type: NodePort